version: '2.32'

volumes:
  postgres_data:

services:
  platform_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: platform_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  backend:
#    build:


